name: Test markdown2image on Windows

on:
  push:
    branches: [ cmake-test ]
  pull_request:
    branches: [ cmake-test ]

jobs:
  build-markdown2image-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-qtwebkit
            mingw-w64-x86_64-gflags
            mingw-w64-x86_64-gtest
            mingw-w64-x86_64-glog
            mingw-w64-x86_64-pybind11

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -G "MinGW Makefiles" -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS="-DGFLAGS_IS_A_DLL=0 -Dgoogle=gflags" -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DWITH_GCOV=OFF -DWITH_ASAN=OFF -DWITH_GLOG=OFF -DWITH_SQLITE=ON -DWITH_TEST=ON -DWITH_TOOLS=ON -DWITH_GAMES=ON

      - name: Build markdown2image
        working-directory: build
        run: mingw32-make markdown2image
